### ISSUE TITLE
Blurred indicator on Big Sur 11.7.3 Intel

### ISSUE THREAD

**Issue by razuit** [thebarbican19/BatteryBoi#27]
![image](https://github.com/thebarbican19/BatteryBoi/assets/3223892/4d81b080-7dc9-436b-be00-407dc18f3dcb)

**Comment by thebarbican19** [comment]
Thanks, I have just published a new release. Please check the app for an update and install it as I am 99% sure this is now resolved. If it is, please close the issue.

**Comment by razuit** [comment]
Thank you for the effort. I installed the latest (2.2.2) and the issue is still there, unfortunately.

**Comment by thebarbican19** [comment]
@razuit sorry about that, I am getting the same outcome. Looking into it further, I should have an update by Thursday/Friday.

**Comment by thebarbican19** [comment]
Hi @razuit. I am pleased to report this is now resolved as I have reworked all the animations, also BLUETOOTH IS IN!
