### ISSUE TITLE
Version 2.3.2 - Modal Timeout Added [INSTANT CRASH]

### ISSUE THREAD

**Issue by iKalamaZoo** [thebarbican19/BatteryBoi#43]
The version 2.3.2 which download name is BatteryBoi-v2.4.2.dmg can't even start in macOS Monterey 12.6.9 (21G726). The version 2.2.2 is still the more stable version with only 1 bug: it gets blurred at startup and right in front of all apps. To fix this issue we need to restart the app every sleep/wake up process.

Again: The version 2.3.2 which download name is BatteryBoi-v2.4.2.dmg can't even start in macOS Monterey 12.6.9 (21G726).

**Comment by thebarbican19** [comment]
@iKalamaZoo, Yeah I know, I broke it for everyone it seems by foolishly not commenting out some untested code. I have just pushed a new version that addresses it.

**Comment by lbydev** [comment]
@thebarbican19  I have downloaded and installed the latest Version 2.3.3 as you suggested, but I am still facing the same issue. Unfortunately, the app is still not opening for me .
 - macOS Monterey 12.6.9 (21G726)

**Comment by thebarbican19** [comment]
Thanks for letting me know. I will keep digging
